// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj9TGp2L2BAoZrTAad4Rv71a6JwgzidvM',
    appId: '1:689249161770:web:7977e4d9138ff2ef452953',
    messagingSenderId: '689249161770',
    projectId: 'globalchat-fc519',
    authDomain: 'globalchat-fc519.firebaseapp.com',
    storageBucket: 'globalchat-fc519.appspot.com',
    measurementId: 'G-VBDDPZ36CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILZZAfGgGXQiYfpEY561dTBa5d3AISd4',
    appId: '1:689249161770:android:950e1d77c0364a36452953',
    messagingSenderId: '689249161770',
    projectId: 'globalchat-fc519',
    storageBucket: 'globalchat-fc519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5xwQudRFp0edaFCdeeH-OrDWA4SFhWw',
    appId: '1:689249161770:ios:b2e2634cf3db3d0a452953',
    messagingSenderId: '689249161770',
    projectId: 'globalchat-fc519',
    storageBucket: 'globalchat-fc519.appspot.com',
    iosBundleId: 'com.example.globalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5xwQudRFp0edaFCdeeH-OrDWA4SFhWw',
    appId: '1:689249161770:ios:b2e2634cf3db3d0a452953',
    messagingSenderId: '689249161770',
    projectId: 'globalchat-fc519',
    storageBucket: 'globalchat-fc519.appspot.com',
    iosBundleId: 'com.example.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj9TGp2L2BAoZrTAad4Rv71a6JwgzidvM',
    appId: '1:689249161770:web:d68602445d340ad6452953',
    messagingSenderId: '689249161770',
    projectId: 'globalchat-fc519',
    authDomain: 'globalchat-fc519.firebaseapp.com',
    storageBucket: 'globalchat-fc519.appspot.com',
    measurementId: 'G-EN7KGHMPPB',
  );
}
